name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Configure Node PATH
        shell: powershell
        run: |
          echo "C:\Program Files\nodejs" >> $env:GITHUB_PATH

      - name: Verify
        shell: powershell
        run: |
          node -v
          npm -v

      - name: Cleanup workspace
        shell: powershell
        run: |
          if (Test-Path node_modules) {
            Remove-Item node_modules -Recurse -Force
          }

          if (Test-Path .next) {
            Remove-Item .next -Recurse -Force
          }

      - name: Install dependencies
        shell: powershell
        run: npm ci

      - name: Build
        shell: powershell
        run: npm run build

      - name: Deploy standalone build
        shell: powershell
        run: |
          robocopy `
            "${{ github.workspace }}\.next\standalone" `
            "C:\Web\GSMANT_FRONT" `
            /MIR

          robocopy `
            "${{ github.workspace }}\public" `
            "C:\Web\GSMANT_FRONT\public" `
            /MIR

          robocopy `
            "${{ github.workspace }}\.next\static" `
            "C:\Web\GSMANT_FRONT\.next\static" `
            /MIR

          if ($LASTEXITCODE -le 3) {
            exit 0
          } else {
            exit $LASTEXITCODE
          }

      - name: Restart PM2
        shell: powershell
        run: |
          cd C:\Web\GSMANT_FRONT
          pm2 restart gsmant_front
