name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Configure Node PATH
        shell: powershell
        run: |
          echo "C:\Program Files\nodejs" >> $env:GITHUB_PATH
          echo "C:\Users\Administrador\AppData\Roaming\npm" >> $env:GITHUB_PATH

      - name: Verify
        shell: powershell
        run: |
          node -v
          npm -v
          pm2 -v

      - name: Cleanup workspace
        shell: powershell
        run: |
          if (Test-Path node_modules) {
            Remove-Item node_modules -Recurse -Force
          }

          if (Test-Path .next) {
            Remove-Item .next -Recurse -Force
          }

      - name: Install dependencies
        shell: powershell
        run: npm ci

      - name: Build
        shell: powershell
        run: npm run build

      - name: Deploy standalone build
        shell: powershell
        run: |

          robocopy `
            "${{ github.workspace }}\.next\standalone" `
            "C:\Web\GSMANT_FRONT" `
            /MIR

          $code = $LASTEXITCODE
          if ($code -gt 3) { exit $code }

          robocopy `
            "${{ github.workspace }}\public" `
            "C:\Web\GSMANT_FRONT\public" `
            /MIR /R:3 /W:5

          $code = $LASTEXITCODE
          if ($code -gt 3) { exit $code }

          robocopy `
            "${{ github.workspace }}\.next\static" `
            "C:\Web\GSMANT_FRONT\.next\static" `
            /MIR /R:3 /W:5

          $code = $LASTEXITCODE
          if ($code -gt 3) { exit $code }

          robocopy `
            "${{ github.workspace }}" `
            "C:\Web\GSMANT_FRONT" `
            ecosystem.config.js

          $code = $LASTEXITCODE
          if ($code -gt 3) { exit $code }
          exit 0

      - name: Start or Restart PM2
        shell: powershell
        run: |
          cd C:\Web\GSMANT_FRONT

          pm2 describe gsmant_front > $null 2>&1

          if ($LASTEXITCODE -eq 0) {
            pm2 restart gsmant_front
          }
          else {
            pm2 start ecosystem.config.js
          }

          pm2 save
